services:
  - type: web
    name: industrial-project-2
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python backend.py
    envVars:
      - key: PORT
        value: 10000
